spring.application.name=ClinicAppointmentSystem
server.port = 8090

spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_appointment_system
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
