create table specialization (
    id bigint generated by default as identity primary key,
    description varchar(255),
    name varchar(255) unique
);

create table patient (
    date_of_birth date,
    gender smallint check (gender between 0 and 1),
    registration_date date,
    id bigint generated by default as identity primary key,
    email varchar(255) unique,
    first_name varchar(255),
    last_name varchar(255),
    phone_number varchar(255)
);

create table doctor (
    consultation_fee double precision,
    years_of_experience integer,
    id bigint generated by default as identity primary key,
    specialization_id bigint,
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    license_number varchar(255) unique,
    phone_number varchar(255),
    constraint fk_doctor_specialization
        foreign key (specialization_id)
        references specialization
);

create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password varchar(255) not null,
    role varchar(255) check (role in ('ADMIN', 'DOCTOR', 'PATIENT'))
);

create table appointment (
    appointment_date date,
    appointment_time time(0),
    doctor_id bigint,
    id bigint generated by default as identity primary key,
    patient_id bigint,
    reason_for_visit varchar(255),
    status varchar(255) check (status in ('SCHEDULED', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW')),
    constraint fk_appointment_doctor
        foreign key (doctor_id)
        references doctor,
    constraint fk_appointment_patient
        foreign key (patient_id)
        references patient
);

create table doctor_schedule (
    day_of_week smallint check (day_of_week between 0 and 6),
    end_time time(0),
    start_time time(0),
    doctor_id bigint,
    id bigint generated by default as identity primary key,
    constraint fk_doctor_schedule_doctor
        foreign key (doctor_id)
        references doctor
);

create table medical_record (
    appointment_id bigint unique,
    id bigint generated by default as identity primary key,
    outcome varchar(255),
    constraint fk_medical_record_appointment
        foreign key (appointment_id)
        references appointment
);

create table prescription (
    id bigint generated by default as identity primary key,
    medical_record_id bigint not null,
    additional_instructions varchar(255),
    dosage varchar(255),
    frequency varchar(255),
    medication_name varchar(255),
    treatment_duration varchar(255),
    constraint fk_prescription_medical_record
        foreign key (medical_record_id)
        references medical_record
);

create table waiting_list_entries (
    appointment_date date not null,
    appointment_time time(0) not null,
    doctor_id bigint not null,
    id bigint generated by default as identity primary key,
    joined_at timestamp(6) not null,
    patient_id bigint not null,
    constraint uk_waiting_list_patient_slot
        unique (patient_id, doctor_id, appointment_date, appointment_time),
    constraint fk_waiting_list_doctor
        foreign key (doctor_id)
        references doctor,
    constraint fk_waiting_list_patient
        foreign key (patient_id)
        references patient
);